export const products = [
  {
    nombre: "Agua purificada",
    clasificacion: "Embotellado",
    entrada: "15-mayo-2025",
    caducidad: "15-mayo-2027",
    prioridad: "Baja",
  },
  {
    nombre: "Jugo de naranja",
    clasificacion: "Embotellado",
    entrada: "01-abril-2025",
    caducidad: "01-octubre-2025",
    prioridad: "Media",
  },
  {
    nombre: "Leche UHT",
    clasificacion: "Embotellado",
    entrada: "10-marzo-2025",
    caducidad: "10-septiembre-2025",
    prioridad: "Media",
  },
  {
    nombre: "Aceite de oliva",
    clasificacion: "Embotellado",
    entrada: "20-enero-2025",
    caducidad: "20-enero-2027",
    prioridad: "Baja",
  },
  {
    nombre: "Salsa de tomate",
    clasificacion: "Embotellado",
    entrada: "05-febrero-2025",
    caducidad: "05-febrero-2026",
    prioridad: "Media",
  },
  {
    nombre: "Atún enlatado",
    clasificacion: "Enlatado",
    entrada: "01-julio-2024",
    caducidad: "01-julio-2027",
    prioridad: "Media",
  },
  {
    nombre: "Maíz enlatado",
    clasificacion: "Enlatado",
    entrada: "10-junio-2024",
    caducidad: "10-junio-2027",
    prioridad: "Baja",
  },
  {
    nombre: "Frijoles refritos enlatados",
    clasificacion: "Enlatado",
    entrada: "25-marzo-2025",
    caducidad: "25-marzo-2028",
    prioridad: "Baja",
  },
  {
    nombre: "Sopa de champiñones enlatada",
    clasificacion: "Enlatado",
    entrada: "12-abril-2025",
    caducidad: "12-abril-2027",
    prioridad: "Media",
  },
  {
    nombre: "Duraznos en almíbar enlatados",
    clasificacion: "Enlatado",
    entrada: "18-enero-2025",
    caducidad: "18-enero-2028",
    prioridad: "Baja",
  },
  {
    nombre: "Manzanas",
    clasificacion: "Perecedero",
    entrada: "28-mayo-2025",
    caducidad: "11-junio-2025",
    prioridad: "Alta",
  },
  {
    nombre: "Pechuga de pollo",
    clasificacion: "Perecedero",
    entrada: "28-mayo-2025",
    caducidad: "31-mayo-2025",
    prioridad: "Alta",
  },
  {
    nombre: "Lechuga",
    clasificacion: "Perecedero",
    entrada: "28-mayo-2025",
    caducidad: "04-junio-2025",
    prioridad: "Alta",
  },
  {
    nombre: "Huevos",
    clasificacion: "Perecedero",
    entrada: "20-mayo-2025",
    caducidad: "20-junio-2025",
    prioridad: "Media",
  },
  {
    nombre: "Yogur",
    clasificacion: "Perecedero",
    entrada: "25-mayo-2025",
    caducidad: "08-junio-2025",
    prioridad: "Alta",
  },
  {
    nombre: "Pasta seca",
    clasificacion: "Otro",
    entrada: "01-enero-2025",
    caducidad: "01-enero-2028",
    prioridad: "Baja",
  },
  {
    nombre: "Arroz",
    clasificacion: "Otro",
    entrada: "10-febrero-2025",
    caducidad: "10-febrero-2029",
    prioridad: "Baja",
  },
  {
    nombre: "Azúcar",
    clasificacion: "Otro",
    entrada: "15-marzo-2025",
    caducidad: "Sin caducidad",
    prioridad: "Baja",
  },
  {
    nombre: "Café molido",
    clasificacion: "Otro",
    entrada: "20-abril-2025",
    caducidad: "20-octubre-2025",
    prioridad: "Media",
  },
  {
    nombre: "Galletas",
    clasificacion: "Otro",
    entrada: "05-mayo-2025",
    caducidad: "05-noviembre-2025",
    prioridad: "Media",
  },
];
